### ISSUE TITLE
GCC has an option preventing casting from unsigned to signed

### ISSUE THREAD

**Issue by tiffany352** [mcinglis/c-style#1]
The `-pedantic` option will prevent many such weak casts.

**Comment by mcinglis** [comment]
Can you elaborate? I know that `-Wsign-conversion` enables warnings about implicit conversions that will change signs, but it tends to be more of a pain than necessary, and seems to encourage unsigned variables to spread (e.g. use `size_t` for any parameter to a `calloc`).
